crescendo = [
    [
        {"name": "team_number", "type": "large_integer", "value": "0001"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": True},
        {"name": "floor_pickup", "type": "boolean", "value": True},
        {"name": "climb", "type": "boolean", "value": True},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": True},
        {"name": "speaker_shot", "type": "integer", "value": 4},
        {"name": "speaker_shot", "type": "integer", "value": 5},
        {"name": "speaker_miss", "type": "integer", "value": 2},
        {"name": "amp_shot", "type": "integer", "value": 1},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0002"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": True},
        {"name": "floor_pickup", "type": "boolean", "value": False},
        {"name": "climb", "type": "boolean", "value": True},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": True},
        {"name": "shoot_distance", "type": "multiple_choice", "value": "Close"},
        {"name": "speaker_shot", "type": "integer", "value": 2},
        {"name": "amp_shot", "type": "integer", "value": 1},
        {"name": "speaker_shot", "type": "integer", "value": 1},
        {"name": "amp_shot", "type": "integer", "value": 5},
        {"name": "amp_miss", "type": "integer", "value": 1},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0003"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": False},
        {"name": "floor_pickup", "type": "boolean", "value": True},
        {"name": "climb", "type": "boolean", "value": True},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": False},
        {"name": "moved_during_auto", "type": "boolean", "value": False},
        {"name": "notes", "type": "text", "value": "No auton, launcher was unreliable"},
        {"name": "speaker_shot", "type": "integer", "value": 3},
        {"name": "speaker_miss", "type": "integer", "value": 4},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0004"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": True},
        {"name": "floor_pickup", "type": "boolean", "value": True},
        {"name": "climb", "type": "boolean", "value": False},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": True},
        {"name": "notes", "type": "text", "value": "Good speaker bot"},
        {"name": "shoot_distance", "type": "multiple_choice", "value": "Close"},
        {"name": "speaker_shot", "type": "integer", "value": 4},
        {"name": "speaker_shot", "type": "integer", "value": 9},
        {"name": "speaker_miss", "type": "integer", "value": 2},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0005"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": False},
        {"name": "floor_pickup", "type": "boolean", "value": False},
        {"name": "climb", "type": "boolean", "value": False},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": True},
        {"name": "shoot_distance", "type": "multiple_choice", "value": "Close"},
        {"name": "speaker_shot", "type": "integer", "value": 1},
        {"name": "amp_shot", "type": "integer", "value": 5},
        {"name": "amp_miss", "type": "integer", "value": 1},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0006"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": True},
        {"name": "floor_pickup", "type": "boolean", "value": False},
        {"name": "climb", "type": "boolean", "value": False},
        {"name": "scored_trap", "type": "boolean", "value": True},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": False},
        {"name": "notes", "type": "text", "value": "Scored trap"},
        {"name": "speaker_shot", "type": "integer", "value": 2},
        {"name": "speaker_shot", "type": "integer", "value": 4},
        {"name": "speaker_miss", "type": "integer", "value": 3},
        {"name": "amp_shot", "type": "integer", "value": 1},
    ],
]
