crescendo = [
    [
        {"name": "team_number", "type": "large_integer", "value": "0001"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": True},
        {"name": "floor_pickup", "type": "boolean", "value": True},
        {"name": "climb", "type": "boolean", "value": True},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": True},
        {"name": "speaker_shot", "type": "integer", "value": 4},
        {"name": "speaker_shot", "type": "integer", "value": 5},
        {"name": "speaker_miss", "type": "integer", "value": 2},
        {"name": "amp_shot", "type": "integer", "value": 1},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0002"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": True},
        {"name": "floor_pickup", "type": "boolean", "value": False},
        {"name": "climb", "type": "boolean", "value": True},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": True},
        {"name": "shoot_distance", "type": "multiple_choice", "value": "Close"},
        {"name": "speaker_shot", "type": "integer", "value": 2},
        {"name": "amp_shot", "type": "integer", "value": 1},
        {"name": "speaker_shot", "type": "integer", "value": 1},
        {"name": "amp_shot", "type": "integer", "value": 5},
        {"name": "amp_miss", "type": "integer", "value": 1},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0003"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": False},
        {"name": "floor_pickup", "type": "boolean", "value": True},
        {"name": "climb", "type": "boolean", "value": True},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": False},
        {"name": "moved_during_auto", "type": "boolean", "value": False},
        {"name": "notes", "type": "text", "value": "No auton, launcher was unreliable"},
        {"name": "speaker_shot", "type": "integer", "value": 3},
        {"name": "speaker_miss", "type": "integer", "value": 4},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0004"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": True},
        {"name": "floor_pickup", "type": "boolean", "value": True},
        {"name": "climb", "type": "boolean", "value": False},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": True},
        {"name": "notes", "type": "text", "value": "Good speaker bot"},
        {"name": "shoot_distance", "type": "multiple_choice", "value": "Close"},
        {"name": "speaker_shot", "type": "integer", "value": 4},
        {"name": "speaker_shot", "type": "integer", "value": 9},
        {"name": "speaker_miss", "type": "integer", "value": 2},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0005"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": False},
        {"name": "floor_pickup", "type": "boolean", "value": False},
        {"name": "climb", "type": "boolean", "value": False},
        {"name": "scored_trap", "type": "boolean", "value": False},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": True},
        {"name": "shoot_distance", "type": "multiple_choice", "value": "Close"},
        {"name": "speaker_shot", "type": "integer", "value": 1},
        {"name": "amp_shot", "type": "integer", "value": 5},
        {"name": "amp_miss", "type": "integer", "value": 1},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "0006"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "left_starting_zone", "type": "boolean", "value": True},
        {"name": "floor_pickup", "type": "boolean", "value": False},
        {"name": "climb", "type": "boolean", "value": False},
        {"name": "scored_trap", "type": "boolean", "value": True},
        {"name": "feeder_station_pickup", "type": "boolean", "value": True},
        {"name": "moved_during_auto", "type": "boolean", "value": False},
        {"name": "notes", "type": "text", "value": "Scored trap"},
        {"name": "speaker_shot", "type": "integer", "value": 2},
        {"name": "speaker_shot", "type": "integer", "value": 4},
        {"name": "speaker_miss", "type": "integer", "value": 3},
        {"name": "amp_shot", "type": "integer", "value": 1},
    ],
]

reefscape = [
    [
        {"name": "team_number", "type": "large_integer", "value": "1"},
        {"name": "match_number", "type": "large_integer", "value": "001"},
        {"name": "auton_moved", "type": "boolean", "value": True},
        {"name": "feeder_pickup", "type": "boolean", "value": True},
        {"name": "park_in_barge_zone", "type": "boolean", "value": False},
        {"name": "climb_shallow", "type": "boolean", "value": True},
        {"name": "climb_deep", "type": "boolean", "value": False},
        {"name": "coral_levels", "type": "multiple_choice", "value": "Level 1"},
        {"name": "auton_coral_scored", "type": "integer", "value": 2},
        {"name": "coral_scored", "type": "integer", "value": 4},
        {"name": "algae_scored_in_processor", "type": "integer", "value": 2},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "2"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "auton_moved", "type": "boolean", "value": True},
        {"name": "feeder_pickup", "type": "boolean", "value": False},
        {"name": "park_in_barge_zone", "type": "boolean", "value": True},
        {"name": "climb_shallow", "type": "boolean", "value": False},
        {"name": "climb_deep", "type": "boolean", "value": False},
        {
            "name": "notes",
            "type": "text",
            "value": "Could score in the reef but only on level 1",
        },
        {"name": "coral_levels", "type": "multiple_choice", "value": "Level 1"},
        {"name": "auton_coral_scored", "type": "integer", "value": 1},
        {"name": "auton_algae_scored_in_processor", "type": "integer", "value": 1},
        {"name": "algae_scored_in_net", "type": "integer", "value": 2},
        {"name": "algae_scored_in_processor", "type": "integer", "value": 3},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "3"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "auton_moved", "type": "boolean", "value": True},
        {"name": "feeder_pickup", "type": "boolean", "value": True},
        {"name": "park_in_barge_zone", "type": "boolean", "value": False},
        {"name": "climb_shallow", "type": "boolean", "value": True},
        {"name": "climb_deep", "type": "boolean", "value": False},
        {"name": "notes", "type": "text", "value": "Good coral scoring bot"},
        {"name": "coral_levels", "type": "multiple_choice", "value": "Level 1"},
        {"name": "auton_coral_scored", "type": "integer", "value": 4},
        {"name": "coral_scored", "type": "integer", "value": 6},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "4"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "auton_moved", "type": "boolean", "value": False},
        {"name": "feeder_pickup", "type": "boolean", "value": False},
        {"name": "park_in_barge_zone", "type": "boolean", "value": True},
        {"name": "climb_shallow", "type": "boolean", "value": False},
        {"name": "climb_deep", "type": "boolean", "value": False},
        {"name": "notes", "type": "text", "value": "No auton, no climb"},
        {"name": "algae_scored_in_net", "type": "integer", "value": 3},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "5"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "auton_moved", "type": "boolean", "value": True},
        {"name": "feeder_pickup", "type": "boolean", "value": False},
        {"name": "park_in_barge_zone", "type": "boolean", "value": True},
        {"name": "climb_shallow", "type": "boolean", "value": False},
        {"name": "climb_deep", "type": "boolean", "value": False},
        {"name": "coral_levels", "type": "multiple_choice", "value": "Level 1"},
        {"name": "auton_algae_scored_in_processor", "type": "integer", "value": 1},
        {"name": "coral_scored", "type": "integer", "value": 2},
        {"name": "algae_scored_in_net", "type": "integer", "value": 1},
        {"name": "algae_scored_in_processor", "type": "integer", "value": 2},
    ],
    [
        {"name": "team_number", "type": "large_integer", "value": "6"},
        {"name": "match_number", "type": "large_integer", "value": "1"},
        {"name": "auton_moved", "type": "boolean", "value": False},
        {"name": "feeder_pickup", "type": "boolean", "value": False},
        {"name": "park_in_barge_zone", "type": "boolean", "value": True},
        {"name": "climb_shallow", "type": "boolean", "value": False},
        {"name": "climb_deep", "type": "boolean", "value": False},
        {"name": "notes", "type": "text", "value": "Only net bot"},
        {"name": "algae_scored_in_net", "type": "integer", "value": 4},
    ],
]
