crescendo = [
    {
        "name": "Team Number",
        "simple_name": "team_number",
        "section": "Main/Team Number",
        "type": "integer",
        "required": "true",
    },
    {
        "name": "Match Number",
        "simple_name": "match_number",
        "section": "Main/Match Number",
        "type": "integer",
        "required": "true",
    },
    {
        "name": "Speaker Shot",
        "simple_name": "speaker_shot",
        "section": "Auton/Speaker Shot",
        "type": "choice",
        "choices": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        "required": "false",
    },
    {
        "name": "Amp Shot",
        "simple_name": "amp_shot",
        "section": "Auton/Amp Shot",
        "type": "choice",
        "choices": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        "required": "false",
    },
    {
        "name": "Speaker Shot",
        "simple_name": "speaker_shot",
        "section": "Teleop/Speaker/Shots",
        "type": "choice",
        "choices": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        "required": "false",
    },
    {
        "name": "Speaker Misses",
        "simple_name": "speaker_miss",
        "section": "Teleop/Speaker/Misses",
        "type": "choice",
        "choices": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        "required": "false",
    },
    {
        "name": "Amp Shots",
        "simple_name": "amp_shot",
        "section": "Teleop/Amp/Shots",
        "type": "choice",
        "choices": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        "required": "false",
    },
    {
        "name": "Amp Misses",
        "simple_name": "amp_miss",
        "section": "Teleop/Amp/Misses",
        "type": "choice",
        "choices": ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        "required": "false",
    },
    {
        "name": "Left Starting Zone",
        "simple_name": "left_starting_zone",
        "section": "Extra Information/Left Starting Zone",
        "type": "choice",
        "required": "false",
    },
    {
        "name": "Shoot Distance",
        "simple_name": "shoot_distance",
        "section": "Extra Information/Shoot Distance",
        "type": "multiple_choice",
        "choices": ["Close", "Mid Field", "Far"],
        "required": "false",
    },
    {
        "name": "Floor Pickup",
        "simple_name": "floor_pickup",
        "section": "Extra Information/Floor Pickup",
        "type": "choice",
        "required": "false",
    },
    {
        "name": "Climb",
        "simple_name": "climb",
        "section": "Extra Information/Climb",
        "type": "choice",
        "required": "false",
    },
    {
        "name": "Scored Trap",
        "simple_name": "scored_trap",
        "section": "Extra Information/Scored Trap",
        "type": "choice",
        "required": "false",
    },
    {
        "name": "Feeder Station Pickup",
        "simple_name": "feeder_station_pickup",
        "section": "Extra Information/Feeder Station Pickup",
        "type": "choice",
        "required": "false",
    },
    {
        "name": "Moved During Auto",
        "simple_name": "moved_during_auto",
        "section": "Extra Information/Moved During Auto",
        "type": "choice",
        "required": "false",
    },
]
