# Generated by Django 5.1.2 on 2025-01-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
