# Generated by Django 5.1.2 on 2025-01-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_verificationcode_user_uuid_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
