# Generated by Django 5.1.2 on 2024-10-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[('2024', '2024')])),
                ('event', models.CharField(max_length=999)),
                ('event_code', models.CharField(max_length=99)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
