# Generated by Django 5.1.2 on 2024-10-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'Data'},
        ),
        migrations.AlterModelOptions(
            name='seasonfields',
            options={'verbose_name_plural': 'Season Fields'},
        ),
        migrations.AlterField(
            model_name='seasonfields',
            name='data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
