# Generated by Django 5.1.2 on 2024-10-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_data_options_alter_seasonfields_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.IntegerField(choices=[('2024', 2024)]),
        ),
        migrations.AlterField(
            model_name='seasonfields',
            name='year',
            field=models.IntegerField(choices=[('2024', 2024)]),
        ),
    ]
