# Generated by Django 5.1.2 on 2024-10-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_data_year_alter_seasonfields_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.IntegerField(choices=[(2024, '2024')]),
        ),
        migrations.AlterField(
            model_name='seasonfields',
            name='year',
            field=models.IntegerField(choices=[(2024, '2024')]),
        ),
    ]
