# Generated by Django 5.1.2 on 2024-10-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_data_year_alter_seasonfields_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeasonFields',
        ),
    ]
