# Generated by Django 5.1.2 on 2024-10-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delete_seasonfields'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
