# Generated by Django 5.1.2 on 2024-11-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_data_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2024, '2024')])),
                ('name', models.CharField(max_length=999)),
                ('event_code', models.CharField(max_length=99)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='event_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.event'),
        ),
    ]
