# Generated by Django 5.1.2 on 2024-11-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_event_data_event_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
