# Generated by Django 5.1.2 on 2024-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_event_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='custom_data',
            field=models.JSONField(blank=True, default={'end_date': '', 'location': '', 'name': 'Custom Event', 'start_date': ''}),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, max_length=99),
        ),
    ]
