# Generated by Django 5.1.2 on 2024-11-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_event_custom_data_alter_event_event_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
