# Generated by Django 5.1.2 on 2025-01-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_data_user_created_event_user_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='team_number_created',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='data',
            name='username_created',
            field=models.CharField(blank=True, max_length=999),
        ),
        migrations.AlterField(
            model_name='data',
            name='year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='year',
            field=models.IntegerField(choices=[(2024, '2024'), (2025, '2025')]),
        ),
    ]
