# Generated by Django 5.1.2 on 2025-01-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_data_team_number_created_data_username_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='account',
            field=models.BooleanField(default=False),
        ),
    ]
