# Generated by Django 5.1.2 on 2025-02-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_data_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_number', models.CharField(max_length=6)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.event')),
            ],
        ),
    ]
