# Generated by Django 5.1.2 on 2025-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_pit_event_pitgroup_pit_pit_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pit',
            name='data',
            field=models.JSONField(default=list),
        ),
    ]
