# Generated by Django 5.1.2 on 2025-02-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_pit_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='pit',
            name='nickname',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
