# Generated by Django 5.1.2 on 2025-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_pit_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='team_number',
            field=models.IntegerField(blank=True, max_length=99, null=True),
        ),
    ]
