# Generated by Django 5.1.2 on 2025-04-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_data_team_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='team_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
