# Generated by Django 5.1.2 on 2025-04-16 14:16

import json
from django.db import migrations


def migrate_json_data(apps, schema_editor):
    Data = apps.get_model("main", "Data")

    for obj in Data.objects.all():
        try:
            # Safely handle both string or already-parsed list
            data = obj.data if isinstance(obj.data, list) else json.loads(obj.data)
        except json.JSONDecodeError:
            continue  # Skip bad data

        if not isinstance(data, list):
            continue  # Ensure it's a list of fields

        team_number = next(
            (
                field.get("value")
                for field in data
                if field.get("name") == "team_number"
            ),
            None,
        )
        if team_number:
            try:
                obj.team_number = int(team_number)
                obj.save()
                print(f"Updated team number for ID {obj.id}: {team_number}")
            except ValueError:
                continue  # Handle bad integer conversion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0021_alter_data_team_number"),
    ]

    operations = [migrations.RunPython(migrate_json_data)]
