# Generated by Django 5.1.2 on 2025-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0022_add_team_number_to_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="pit",
            name="uuid",
            field=models.UUIDField(blank=True, null=True),
        )
    ]
