# Generated by Django 5.1.2 on 2025-04-19 14:28

from django.db import migrations
import uuid


def add_uuid(apps, schema_editor):
    Pit = apps.get_model("main", "Pit")
    for pit in Pit.objects.all():
        pit.uuid = uuid.uuid4()
        pit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0023_pit_uuid"),
    ]

    operations = [
        migrations.RunPython(add_uuid),
    ]
