# Generated by Django 5.1.2 on 2025-04-23 14:52

from django.db import migrations
import uuid


def add_uuid(apps, schema_editor):
    Pit = apps.get_model("main", "Pit")
    for pit in Pit.objects.all():
        updated_data = []
        for question in pit.data:
            try:
                for answer in question.get("answers", []):
                    answer["uuid"] = str(uuid.uuid4())
            except Exception:
                pass
            updated_data.append(question)

        pit.data = updated_data
        pit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0024_add_uuid_to_pits"),
    ]

    operations = [
        migrations.RunPython(add_uuid),
    ]
